---
title: "Chapter 1: Exercise 1"
author: "Colin Gillespie (Xiang Li)"
output:
  html_document
#toc: true
#number_sections: true
# add {.tabset} to the end of First level Header
---


## Instructions 

For each line below:
  
  1. Format the line with markdown to display what the line describes.
  2. Re-render the file by pressing the `Knit HTML` button above to see if it worked.
  3. Move on to the next line.
  
The Markdown cheatsheet is available under the `Help` button in the top menu.
***

## Exercises 

### Use markdown to indicate:

A first level header  

# Header 

A second level header

## Header 

A third level header  

### Header 

A fourth level header

#### Header

A fifth level header

##### Header

A sixth level header  

###### Header 

bold text  
**bold text**
OR
__bold text__

italic text
*bold text*
OR
_bold text_

An unordered list:  
Item 1  
Item 2  
sub-item 1  
sub-item 2  

* Item 1
* Item 2
    + Item 2a
    + Item 2b
    
An ordered list:  
Item 1  
Item 2  
sub-item 1  
sub-item 2  

1. Item 1
2. Item 2
3. Item 3
    + Item 3a
    + Item 3b
    
A table:  
Header 1 Header 2  
Cell 1 Cell 2  
Cell 3 Cell 4  

First Header  | Second Header
------------- | -------------
Content Cell  | Content Cell
Content Cell  | Content Cell


```{r}
library("gapminder")
data(gapminder, package = "gapminder")
plot(lifeExp~gdpPercap, data = gapminder)
library(d3heatmap)
d3heatmap(mtcars)
```

echo = true : show codes (default)
echo = false : no show

eval = true : run codes (default)
eval = false : don't run codes

include = true :  show outputs (default)
include = false : no show

\newline
<!-- in-text reference r -->
Colnames of data __mtcar__ are `r names(mtcars)`


